apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app6.fullname" . }}
  labels:
    {{- include "app6.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app6.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app6.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app6.image.repository }}:{{ .Values.app6.image.tag }}"
          imagePullPolicy: {{ .Values.app6.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.containerPort }}
