apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-qa
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: app6
            chartPath: charts/app6
            image: docker.io/rajarammurali513/app6
            semver: ~1
          - name: app7
            chartPath: charts/app7
            image: docker.io/rajarammurali513/app7
            semver: ~1
          - name: app8
            chartPath: charts/app8
            image: docker.io/rajarammurali513/app8
            semver: ~1
          - name: app9
            chartPath: charts/app9
            image: docker.io/rajarammurali513/app9
            semver: ~1
          - name: app10
            chartPath: charts/app10
            image: docker.io/rajarammurali513/app10
            semver: ~1

  template:
    metadata:
      name: '{{name}}-qa'
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: '{{name}}={{image}}:{{semver}}'
        argocd-image-updater.argoproj.io/{{name}}.helm.image-name: '{{name}}.image.repository'
        argocd-image-updater.argoproj.io/{{name}}.helm.image-tag: '{{name}}.image.tag'
        argocd-image-updater.argoproj.io/{{name}}.update-strategy: semver
        argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-secret
        argocd-image-updater.argoproj.io/write-back-target: 'helmvalues:/envs/qa/app-values.yaml'
    spec:
      project: qa
      source:
        repoURL: https://github.com/rajaramiotfal/sample-argocd-helm-5appsdd.git
        targetRevision: main
        path: '{{chartPath}}'
        helm:
          valueFiles:
            - '$repo/envs/qa/app-values.yaml'
      destination:
        server: https://kubernetes.docker.internal:6443
        namespace: qa-ns
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
