apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-${ENV_NAME}
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # 1️⃣ Environment list
          - list:
              elements:
                - env: ${ENV_NAME}
                  ns: ${NS_NAME}
                  writeBack: ${WRITEBACK_METHOD}
          # 2️⃣ Application list (with chart path & image)
          - list:
              elements:
                - name: app1
                  chartPath: charts/app1
                  image: docker.io/rajarammurali513/app1
                  semver: "~1"
                  syncWave: "1"
                - name: app2
                  chartPath: charts/app2
                  image: docker.io/rajarammurali513/app2
                  semver: "~1"
                  syncWave: "2"
                - name: app3
                  chartPath: charts/app3
                  image: docker.io/rajarammurali513/app3
                  semver: "~1"
                  syncWave: "3"
                - name: app4
                  chartPath: charts/app4
                  image: docker.io/rajarammurali513/app4
                  semver: "~1"
                  syncWave: "4"
                - name: app5
                  chartPath: charts/app5
                  image: docker.io/rajarammurali513/app5
                  semver: "~1"
                  syncWave: "5"

  template:
    metadata:
      name: '{{name}}-{{env}}'
      namespace: argocd
      labels:
        env: '{{env}}'
        app: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
        argocd-image-updater.argoproj.io/image-list: '{{name}}={{image}}:{{semver}}'
        argocd-image-updater.argoproj.io/{{name}}.helm.image-name: '{{name}}.image.repository'
        argocd-image-updater.argoproj.io/{{name}}.helm.image-tag: '{{name}}.image.tag'
        argocd-image-updater.argoproj.io/{{name}}.update-strategy: semver
        argocd-image-updater.argoproj.io/write-back-method: '{{writeBack}}:secret:argocd/argocd-image-updater-secret'
        argocd-image-updater.argoproj.io/write-back-target: 'helmvalues:/envs/{{env}}/app-values.yaml'
    spec:
      project: '{{env}}'
      source:
        repoURL: https://github.com/rajaramiotfal/sample-argocd-helm-5appsdd.git
        targetRevision: main
        path: '{{chartPath}}'
        helm:
          valueFiles:
            - '$repo/envs/{{env}}/app-values.yaml'
          parameters:
            - name: env
              value: '{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ns}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
