apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-${ENV_NAME}
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: ${ENV_NAME}
                  ns: ${NS_NAME}
                  writeBack: ${WRITEBACK_METHOD}
          - list:
              elements:
                - name: charts/app6
                  chartPath: charts/app6
                  image: docker.io/rajarammurali513/app6
                  semver: "~1"
                  syncWave: "1"
                - name: charts/app7
                  chartPath: charts/app7
                  image: docker.io/rajarammurali513/app7
                  semver: "~1"
                  syncWave: "2"
                - name: charts/app8
                  chartPath: charts/app8
                  image: docker.io/rajarammurali513/app8
                  semver: "~1"
                  syncWave: "3"
                - name: charts/app9
                  chartPath: charts/app9
                  image: docker.io/rajarammurali513/app9
                  semver: "~1"
                  syncWave: "4"
                - name: charts/app10
                  chartPath: charts/app10
                  image: docker.io/rajarammurali513/app10
                  semver: "~1"
                  syncWave: "5"
                  
  template:
    metadata:
      name: '{{name}}-{{env}}'
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
        argocd-image-updater.argoproj.io/image-list: '{{name}}={{image}}:{{semver}}'
        argocd-image-updater.argoproj.io/{{name}}.helm.image-name: '{{name}}.image.repository'
        argocd-image-updater.argoproj.io/{{name}}.helm.image-tag: '{{name}}.image.tag'
        argocd-image-updater.argoproj.io/{{name}}.update-strategy: semver
        argocd-image-updater.argoproj.io/write-back-method: '{{writeBack}}:secret:argocd/argocd-image-updater-secret'
        argocd-image-updater.argoproj.io/write-back-target: 'helmvalues:/envs/{{env}}/app-values.yaml'
    spec:
      project: '{{env}}'
      source:
        repoURL: https://github.com/rajaramiotfal/sample-argocd-helm-5appsdd.git
        targetRevision: main
        path: '{{chartPath}}'
        helm:
          valueFiles:
            - '$repo/envs/{{env}}/app-values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ns}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
