env: prod
app6:
  image:
    repository: docker.io/rajarammurali513/app6
    tag: "1.0.0"
app7:
  image:
    repository: docker.io/rajarammurali513/app7
    tag: "1.0.0"
app8:
  image:
    repository: docker.io/rajarammurali513/app8
    tag: "1.0.0"
app9:
  image:
    repository: docker.io/rajarammurali513/app9
    tag: "1.0.0"
app10:
  image:
    repository: docker.io/rajarammurali513/app10
    tag: "1.0.0"
